from enum import Enum


class Color(Enum):
    SUCCESS_PRIMARY = "SUCCESS_PRIMARY"
    SUCCESS_SECONDARY = "SUCCESS_SECONDARY"
    WARNING_PRIMARY = "WARNING_PRIMARY"
    WARNING_SECONDARY = "WARNING_SECONDARY"
    ERROR_PRIMARY = "ERROR_PRIMARY"
    TEXT_PRIMARY = "TEXT_PRIMARY"
    TEXT_SECONDARY = "TEXT_SECONDARY"
    TEXT_HINT = "TEXT_HINT"
    TEXT_DIVIDER = "TEXT_DIVIDER"
    ICON_PRIMARY = "ICON_PRIMARY"
    ICON_SECONDARY = "ICON_SECONDARY"
    ICON_HINT = "ICON_HINT"
    ICON_DIVIDER = "ICON_DIVIDER"
    WHITE_PRIMARY = "WHITE_PRIMARY"
