from enum import Enum


class Color(Enum):
    COLOR_UNSPECIFIED = "COLOR_UNSPECIFIED"
    SUCCESS_PRIMARY = "SUCCESS_PRIMARY"
    SUCCESS_SECONDARY = "SUCCESS_SECONDARY"
    WARNING_PRIMARY = "WARNING_PRIMARY"
    WARNING_SECONDARY = "WARNING_SECONDARY"
    ERROR_PRIMARY = "ERROR_PRIMARY"
