from enum import Enum


class Scope(str, Enum):
    UNKNOWN = 'UNKNOWN'
    POST_ADDON_CREATE = 'POST_ADDON_CREATE'
    USER_PHONE = 'USER_PHONE'
    USER_ADDON_CREATE = 'USER_ADDON_CREATE'
    CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND'
    CHAT_CONVERSATION_READ = 'CHAT_CONVERSATION_READ'
    USER_POSTS_GET = 'USER_POSTS_GET'
    CHAT_POST_CONVERSATIONS_READ = 'CHAT_POST_CONVERSATIONS_READ'
    CHAT_POST_CONVERSATIONS_MESSAGE_SEND = 'CHAT_POST_CONVERSATIONS_MESSAGE_SEND'
    USER_VERIFICATION_CREATE = 'USER_VERIFICATION_CREATE'
    OFFLINE_ACCESS = 'OFFLINE_ACCESS'

    MANAGEMENT_APPS_READ = 'MANAGEMENT_APPS_READ'
    MANAGEMENT_APPS_WRITE = 'MANAGEMENT_APPS_WRITE'

    POST_ONGOING_IMAGES_GET = 'POST_ONGOING_IMAGES_GET'


